exact = true
exclude = []
ignore_type_checking_imports = true
root_module = "dependenciesonly"
source_roots = ["src"]
# forbid_circular_dependencies = true
# TODO(egparedes): try to solve the circular dependencies between
#   gt4py.cartesian and gt4py.storage

layers = ["public", "logic", "infrastructure", "utility"]

[[modules]]
path = "<root>"
depends_on = [
    "gt4py._core",
    "gt4py.eve",
    "gt4py.next.common",
    "gt4py.next.constructors",
    "gt4py.next.ffront",
    "gt4py.next.typing",
    "gt4py.storage",
]
layer = "public"

[[modules]]
path = "gt4py.cartesian"
depends_on = ["gt4py.storage"]
layer = "public"

[[modules]]
paths = [
    "gt4py.next.constructors",
    "gt4py.next.experimental",
    "gt4py.next.typing",
]
depends_on = ["gt4py.storage"]
layer = "public"

[[modules]]
path = "gt4py.storage"
layer = "public"

[[modules]]
paths = [
    "gt4py.next.backend",
    "gt4py.next.embedded",
    "gt4py.next.ffront",
    "gt4py.next.iterator",
    "gt4py.next.program_processors",
    "gt4py.next.toolchain",
]
layer = "logic"


[[modules]]
paths = [
    "gt4py._core",
    "gt4py.next.common",
    "gt4py.next.config",
    "gt4py.next.custom_layout_allocators",
    "gt4py.next.errors",
    "gt4py.next.field_utils",
    "gt4py.next.instrumentation",
    "gt4py.next.named_collections",
    "gt4py.next.otf",
    "gt4py.next.type_system",
    "gt4py.__about__",
]
layer = "infrastructure"

[[modules]]
paths = ["gt4py.next.utils"]
depends_on = ["gt4py.eve"]
layer = "utility"

[[modules]]
paths = ["gt4py.eve"]
depends_on = []
layer = "utility"
