# Tox configuration file
# Read more under https://tox.readthedocs.org/

[tox]
envlist =
    py{310}-{base,atlas}
    eve-py{38,39,310}
    dev-{base,atlas}

[testenv]
passenv = BOOST_ROOT BOOST_HOME CUDA_HOME CUDA_PATH CXX CC OPENMP_CPPFLAGS OPENMP_LDFLAGS PIP_USER PYTHONUSERBASE
whitelist_externals =
    /bin/bash
    make
    gcc
    g++
    ldd
    echo
    cp
    mv
    rm
deps =
    -r {toxinidir}/requirements-dev.txt
install_command = python -m pip install --no-cache-dir {opts} {packages}
commands_pre =
    rm -Rf tests/_reports/coverage*
    atlas: pip install -i https://test.pypi.org/simple/ atlas4py
commands =
    pytest --cache-clear --cov -v -- {posargs}
    pytest --doctest-modules --cov --cov-append -v src/
commands_post =
    coverage report --rcfile=setup.cfg
    coverage html --rcfile=setup.cfg --show-contexts

[testenv:eve-py{38,39,310}]
; Temporary hack to test the eve subpackage with Python 3.8 and 3.9
run_before =
    echo "Patching 'setup.cfg' before installation..."
    cp ./setup.cfg ./setup.cfg.orig
    grep -v python_requires setup.cfg.orig > setup.cfg
commands =
    pytest --cache-clear -v -x -s -- tests/eve_tests
    pytest --doctest-modules -v src/eve
commands_post =
    echo "Restauring original 'setup.cfg'..."
    mv ./setup.cfg.orig ./setup.cfg

[testenv:dev-{base,atlas}]
usedevelop = True
commands_pre =
commands =
commands_post =
